[package]
name = "trojan-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
tokio = { version = "1.38", features = ["macros", "rt-multi-thread", "net", "io-util"] }
native-tls = "0.2.12"
tokio-native-tls = "0.3.1"
rustls-pemfile = "2.1"
hex = "0.4.3"
webpki-roots = "0.26.2"
env_logger = "0.11.3"
log = "0.4.21"
async-trait = "0.1.80"
serde = { version = "1.0.203", features = ["derive"] }
toml = "0.8.14"
sha2 = "0.10.8"

[profile.release]
opt-level = "z"
lto = true
panic = "abort"
strip = true
codegen-units = 1
