[package]
name = "trojan-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
tokio = { version = "1.38", features = ["full"] }
rustls = "0.23"
tokio-rustls = "0.26.0"
rustls-pemfile = "2.1.2"
