[package]
name = "trojan-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
tokio = { version = "1.38", features = ["full"] }
rustls = "0.23"
tokio-rustls = "0.26"
rustls-pemfile = "2.1"
hickory-resolver = "0.24.1"
aws-lc-rs = "1.7"
hex = "0.4.3"
webpki-roots = "0.26.2"
env_logger = "0.11.3"
log = "0.4.21"
