# Listening address and port of the server.
# The port should remain set to 443 in order to seem
# as any ordinary HTTPS server would
listen_addr = "0.0.0.0:443"

# Password for the Trojan Handshake
password = "12345"

# The fallback server (HTTP) should ideally
# server believable seeming content
fallback_addr = "127.0.0.1:8080"

# Uncomment to enable websocket support and specify
# a websocket path
# websocket_path = "/my_websocket"

# Legitimate certificates must be used for your domain
# Self signing is not enabled
certificate_path = "samples/cert.pem"
private_key_path = "samples/private.pem"
