# Listening address and port of the server.
# The port should remain set to 443 in order to seem
# as any ordinary HTTPS server would
listen_addr = "0.0.0.0:2222"

# Password for the Trojan Handshake
password = "12345"

# The fallback server (HTTP) should ideally
# server believable seeming content
fallback_addr = "192.168.0.107:2205"

# Legitimate certificates must be used for your domain
# Self signing is not enabled
certificate_path = "samples/server.pem"
private_key_path = "samples/server.key"

websocket_path = "/naresh"